import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const community=process.argv.includes('--community');
if(community){
  // Refuse to switch the live entry point before the matching database is ready.
  const config=await readFile(path.join(root,'cloud-config.js'),'utf8');
  const url=config.match(/https:\/\/[a-z]+\.supabase\.co/)?.[0];
  const key=config.match(/sb_publishable_[A-Za-z0-9_-]+/)?.[0];
  if(!url||!key)throw Error('Missing public Supabase configuration');
  for(const endpoint of ['blog_posts?select=id,owner_id&limit=1','blog_comments?select=id&limit=1']){
    const response=await fetch(url+'/rest/v1/'+endpoint,{headers:{apikey:key},signal:AbortSignal.timeout(15000)});
    if(!response.ok)throw Error('Community migration is not ready; existing entry point was not changed. '+await response.text());
  }
  const response=await fetch(url+'/rest/v1/rpc/blog_feed',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({page_number:1}),signal:AbortSignal.timeout(15000)});
  if(!response.ok)throw Error('Community feed is not ready; existing entry point was not changed.');
  const feed=await response.json();if(!Array.isArray(feed.items)||typeof feed.total!=='number'||feed.items.some(p=>'body' in p))throw Error('Unexpected community feed response');
  const html=(await readFile(path.join(root,'community-preview.html'),'utf8')).replaceAll('signup-validation-20261002','community-20261002-r2').replace(/(community(?:-api|-auth|-app)?\.(?:css|js))"/g,'$1?v=community-20261002-r2"');
  await writeFile(path.join(root,'index.html'),html);
}
const read=async p=>JSON.parse(await readFile(path.join(root,p),'utf8'));
const data=await read('content/site.json');
// Enterprise records are excluded from all public build output.
delete data.companies;
const navIds=new Set();
function validateNav(nodes){for(const n of nodes){if(!n.id||navIds.has(n.id)||!n.title||!/^#\//.test(n.href))throw Error('Invalid navigation: '+n.id);navIds.add(n.id);if(n.children)validateNav(n.children);}}
validateNav(data.navigation);
const ids=new Set();
const records=[...data.articles,...data.projects,...data.interviews,...data.essays];
for(const item of records){if(!item.id||ids.has(item.id))throw Error('Missing or duplicate ID: '+item.id);ids.add(item.id);}
if(data.folders){
  const folders=new Map();
  for(const f of data.folders){if(!f.id||folders.has(f.id)||!f.name||!['knowledge','projects','interviews','essays'].includes(f.collection))throw Error('Invalid folder: '+f.id);folders.set(f.id,f);}
  for(const f of data.folders){const seen=new Set([f.id]);let p=f.parent_id;while(p){const parent=folders.get(p);if(!parent||parent.collection!==f.collection||seen.has(p))throw Error('Invalid folder parent: '+f.id);seen.add(p);p=parent.parent_id;}}
  for(const [collection,key] of Object.entries({knowledge:'articles',projects:'projects',interviews:'interviews',essays:'essays'}))for(const post of data[key])if(post.folder_id&&folders.get(post.folder_id)?.collection!==collection)throw Error('Invalid post folder: '+post.id);
}
const targets=new Set([...data.articles.map(a=>'article/'+a.id),...data.projects.map(a=>'project/'+a.id),...data.interviews.map(a=>'interview/'+a.id),...data.essays.map(a=>'essay/'+a.id)]);
for(const item of records)for(const related of item.related||[])if(!targets.has(related))throw Error('Broken related link: '+related);
await writeFile(path.join(root,'content.js'),'// Generated by node build.mjs. Edit content/ instead.\nwindow.BLOG = '+JSON.stringify(data,null,2)+';\n');
// Both supported Pages source folders contain the same generated site.
await mkdir(path.join(root,'docs'),{recursive:true});
for(const file of ['index.html','styles.css','app.js','content.js','folders.js','markdown.js','cloud-config.js','cloud.js','admin.html','inline-writer.js','inline-writer.css','forum.css','reference-theme.css','theme.js','landscape.svg','mega-nav.css','reading-writing.css','header-search.css',...(community?['community.css','community-api.js','community-auth.js','community-app.js']:[])])await copyFile(path.join(root,file),path.join(root,'docs',file));
await writeFile(path.join(root,'.nojekyll'),'');
await writeFile(path.join(root,'docs/.nojekyll'),'');
console.log('Built '+records.length+' records; root and docs are ready for GitHub Pages.');
