import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const read=async p=>JSON.parse(await readFile(path.join(root,p),'utf8'));
const data=await read('content/site.json');
// Enterprise records are excluded from all public build output.
delete data.companies;
const ids=new Set();
const records=[...data.articles,...data.projects,...data.interviews];
for(const item of records){if(!item.id||ids.has(item.id))throw Error('Missing or duplicate ID: '+item.id);ids.add(item.id);}
const targets=new Set([...data.articles.map(a=>'article/'+a.id),...data.projects.map(a=>'project/'+a.id),...data.interviews.map(a=>'interview/'+a.id)]);
for(const item of records)for(const related of item.related||[])if(!targets.has(related))throw Error('Broken related link: '+related);
await writeFile(path.join(root,'content.js'),'// Generated by node build.mjs. Edit content/ instead.\nwindow.BLOG = '+JSON.stringify(data,null,2)+';\n');
// Both supported Pages source folders contain the same generated site.
await mkdir(path.join(root,'docs'),{recursive:true});
for(const file of ['index.html','styles.css','app.js','content.js'])await copyFile(path.join(root,file),path.join(root,'docs',file));
await writeFile(path.join(root,'.nojekyll'),'');
await writeFile(path.join(root,'docs/.nojekyll'),'');
console.log('Built '+records.length+' records; root and docs are ready for GitHub Pages.');
