import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const read=async p=>JSON.parse(await readFile(path.join(root,p),'utf8'));
const data=await read('content/site.json');
// Enterprise records are excluded from all public build output.
delete data.companies;
const navIds=new Set();
function validateNav(nodes){for(const n of nodes){if(!n.id||navIds.has(n.id)||!n.title||!/^#\//.test(n.href))throw Error('Invalid navigation: '+n.id);navIds.add(n.id);if(n.children)validateNav(n.children);}}
validateNav(data.navigation);
const ids=new Set();
const records=[...data.articles,...data.projects,...data.interviews,...data.essays];
for(const item of records){if(!item.id||ids.has(item.id))throw Error('Missing or duplicate ID: '+item.id);ids.add(item.id);}
if(data.folders){
  const folders=new Map();
  for(const f of data.folders){if(!f.id||folders.has(f.id)||!f.name||!['knowledge','projects','interviews','essays'].includes(f.collection))throw Error('Invalid folder: '+f.id);folders.set(f.id,f);}
  for(const f of data.folders){const seen=new Set([f.id]);let p=f.parent_id;while(p){const parent=folders.get(p);if(!parent||parent.collection!==f.collection||seen.has(p))throw Error('Invalid folder parent: '+f.id);seen.add(p);p=parent.parent_id;}}
  for(const [collection,key] of Object.entries({knowledge:'articles',projects:'projects',interviews:'interviews',essays:'essays'}))for(const post of data[key])if(post.folder_id&&folders.get(post.folder_id)?.collection!==collection)throw Error('Invalid post folder: '+post.id);
}
const targets=new Set([...data.articles.map(a=>'article/'+a.id),...data.projects.map(a=>'project/'+a.id),...data.interviews.map(a=>'interview/'+a.id),...data.essays.map(a=>'essay/'+a.id)]);
for(const item of records)for(const related of item.related||[])if(!targets.has(related))throw Error('Broken related link: '+related);
await writeFile(path.join(root,'content.js'),'// Generated by node build.mjs. Edit content/ instead.\nwindow.BLOG = '+JSON.stringify(data,null,2)+';\n');
// Both supported Pages source folders contain the same generated site.
await mkdir(path.join(root,'docs'),{recursive:true});
for(const file of ['index.html','styles.css','app.js','content.js','folders.js','markdown.js','cloud-config.js','cloud.js','admin.html','inline-writer.js','inline-writer.css','forum.css','reference-theme.css','theme.js','landscape.svg','mega-nav.css','reading-writing.css'])await copyFile(path.join(root,file),path.join(root,'docs',file));
await writeFile(path.join(root,'.nojekyll'),'');
await writeFile(path.join(root,'docs/.nojekyll'),'');
console.log('Built '+records.length+' records; root and docs are ready for GitHub Pages.');
