import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const {PGlite}=await import('./.test-runtime/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
await db.exec(await readFile('supabase/schema.sql','utf8'));
await db.exec(await readFile('supabase/schema.sql','utf8')); // Migration is rerunnable.
await db.exec(await readFile('supabase/seed.sql','utf8'));
await db.exec(await readFile('supabase/file-operations.sql','utf8'));
const owner='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users(id) values('${owner}'),('${other}');insert into public.blog_authors values('${owner}');`);
async function role(name,id=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+name);}
await role('authenticated',owner);
await db.exec("insert into blog_folders values('test-root','essays','Root',null);insert into blog_folders values('test-child','essays','Child','test-root');insert into blog_posts(id,collection,folder_id,title,body) values('private-test','essays','test-child','Draft','SECRET DRAFT');");
assert.equal((await db.query("select * from blog_posts where id='private-test'")).rows.length,1);
await assert.rejects(db.exec("insert into blog_posts(id,collection,folder_id,title) values('bad','projects','test-child','Wrong collection')"));
await assert.rejects(db.exec("update blog_folders set parent_id='test-child' where id='test-root'"));
await role('anon');
assert.equal((await db.query("select * from blog_posts where id='private-test'")).rows.length,0);
await assert.rejects(db.exec("insert into blog_posts(id,collection,title) values('hack','essays','hack')"));
await role('authenticated',other);
assert.equal((await db.query("select * from blog_posts where id='private-test'")).rows.length,0);
await assert.rejects(db.exec("insert into blog_authors values('"+other+"')"));
await assert.rejects(db.exec("insert into blog_folders values('bad','essays','Bad',null)"));
await assert.rejects(db.exec("insert into blog_posts(id,collection,title) values('hack','essays','hack')"));
assert.equal((await db.query("update blog_posts set published=true where id='private-test' returning id")).rows.length,0);
await role('authenticated',owner);
let published=(await db.query("update blog_posts set published=true where id='private-test' and version=1 returning *")).rows[0];assert.equal(published.version,2);
assert.equal((await db.query("update blog_posts set body='stale' where id='private-test' and version=1 returning id")).rows.length,0);
await role('anon');assert.equal((await db.query("select * from blog_posts where id='private-test'")).rows.length,1);
await role('authenticated',owner);await db.exec("update blog_posts set published=false where id='private-test'");
await role('anon');assert.equal((await db.query("select * from blog_posts where id='private-test'")).rows.length,0);
await assert.rejects(db.query("select blog_file_operation('delete_post','private-test',3)"));
await role('authenticated',other);
await assert.rejects(db.query("select blog_file_operation('delete_post','private-test',3)"));
await role('authenticated',owner);
await assert.rejects(db.query("select blog_file_operation('move_folder','test-root',1,null,'test-child')"));
await assert.rejects(db.query("select blog_file_operation('delete_folder','test-child',1)"));
await db.query("select blog_file_operation('rename_folder','test-child',1,'Renamed')");
await assert.rejects(db.query("select blog_file_operation('rename_folder','test-child',1,'Stale')"));
await db.query("select blog_file_operation('move_folder','test-child',2,null,null)");
await db.query("select blog_file_operation('delete_post','private-test',3)");
await db.query("select blog_file_operation('delete_folder','test-child',3)");
assert.equal((await db.query("select * from blog_folders where id='test-child'")).rows.length,0);
await db.close();
const context={};context.window=context;vm.createContext(context);vm.runInContext(await readFile('markdown.js','utf8'),context);
const render=context.BlogMarkdown.render;
assert.match(render('## Title\n\n- one\n- two\n\n```js\n<script>\n```'),/<h3>Title<\/h3>/);
assert.match(render('**Bold** [link](https://example.com)'),/<strong>Bold<\/strong>/);
assert.doesNotMatch(render('<img src=x onerror=alert(1)> [bad](javascript:alert(1))'),/<img|href="javascript:/);
assert.doesNotMatch(render('[x](https://a.test/"onmouseover="alert(1))'),/href="[^>]*"onmouseover="/);
assert.match(render('```\nunclosed <script>'),/&lt;script&gt;/);
console.log('PASS: PostgreSQL RLS, writer allowlist, draft isolation, publish/withdraw, folder constraints, stale updates and Markdown escaping.');

// HTTP adapter exercises real request serialization with deterministic mock responses.
const requests=[],queue=[];
const apiContext={AbortSignal,Date,console,fetch:async(url,options)=>{requests.push({url,options});const value=queue.shift();assert.ok(value,'Unexpected network request');return {ok:value.status<400,status:value.status,text:async()=>JSON.stringify(value.body)};}};
apiContext.window=apiContext;apiContext.CLOUD_CONFIG={url:'https://test.supabase.co',key:'sb_publishable_test'};
vm.createContext(apiContext);vm.runInContext(await readFile('cloud.js','utf8'),apiContext);
const api=apiContext.BlogCloud;
queue.push({status:200,body:[]},{status:200,body:[]});await api.load();
assert.ok(requests.some(r=>r.url.includes('published=eq.true')));
assert.ok(requests.every(r=>!r.options.headers.Authorization));
queue.push({status:200,body:{access_token:'test-jwt',refresh_token:'test-refresh',expires_in:3600,user:{id:'test-user'}}},{status:200,body:[{user_id:'test-user'}]});
await api.login('writer@example.test','test-only');
assert.equal(requests.at(-1).options.headers.Authorization,'Bearer test-jwt');
queue.push({status:200,body:[]});await assert.rejects(api.save({id:'post-id',title:'Edited'},1),/其他窗口修改/);
assert.ok(requests.at(-1).url.endsWith('id=eq.post-id&version=eq.1'));
queue.push({status:200,body:null});await api.logout();await assert.rejects(api.save({id:'x'}),/请先登录/);
queue.push({status:200,body:{access_token:'test-jwt',expires_in:3600,user:{id:'other'}}},{status:200,body:[]});
await assert.rejects(api.login('other@example.test','test-only'),/尚未被配置/);
queue.push({status:404,body:{code:'PGRST205'}});await assert.rejects(api.request('/missing'),/尚未初始化/);
assert.equal(queue.length,0);
console.log('PASS: public-read filtering, authentication, writer membership, version filtering, logout and setup errors.');
