import {JSDOM} from './.test-runtime/node_modules/jsdom/lib/api.js';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
assert.doesNotMatch(await readFile('styles.css','utf8'),/(^|[{},])nav(?=[\s.{:#])/,'Header rules must not affect article navigation or pagination');
const html=await readFile('community-preview.html','utf8');
const dom=new JSDOM(html,{url:'https://knaios.github.io/cai.github.io/#/posts',runScripts:'outside-only'}),w=dom.window,d=w.document;
w.structuredClone=structuredClone;w.scrollTo=()=>{};w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.confirm=()=>true;
const aid='00000000-0000-0000-0000-000000000001',bid='00000000-0000-0000-0000-000000000002';
const profiles=[{user_id:aid,username:'alice',display_name:'Alice',bio:'A bio',website:''},{user_id:bid,username:'bob',display_name:'Bob',bio:'B bio',website:''}];
const users={alice:{id:aid,email_confirmed_at:'2026-10-02',isAuthor:false,user_metadata:{username:'alice'}},bob:{id:bid,email_confirmed_at:'2026-10-02',isAuthor:false,user_metadata:{username:'bob'}}};
const folders=[{id:'a-folder',owner_id:aid,collection:'knowledge',parent_id:null,name:'Alice folder',version:1},{id:'b-folder',owner_id:bid,collection:'knowledge',parent_id:null,name:'Bob folder',version:1}];
folders.push({id:'b-child',owner_id:bid,collection:'knowledge',parent_id:'b-folder',name:'Nested collection',version:1});
const posts=[{id:'a-post',owner_id:aid,collection:'knowledge',folder_id:'a-folder',title:'Alice public',summary:'A summary',body:'## Heading\n\nAlice body',metadata:{},published:true,version:1,created_at:'2026-10-02'},{id:'a-draft',owner_id:aid,collection:'knowledge',folder_id:'a-folder',title:'SECRET draft',summary:'SECRET',body:'PRIVATE',metadata:{},published:false,version:1,created_at:'2026-10-02'},{id:'b-post',owner_id:bid,collection:'knowledge',folder_id:'b-folder',title:'Bob public',summary:'B summary',body:'Bob body',metadata:{},published:true,version:1,created_at:'2026-10-02'}];
for(let i=0;i<22;i++)posts.push({id:'page-'+i,owner_id:bid,collection:'essays',title:'Essay '+i,body:'Essay',summary:'',metadata:{},published:true,version:1,folder_id:null,created_at:'2026-10-01'});
for(const p of posts){p.metadata.forum_sync=true;p.metadata.forum_section=p.collection==='knowledge'?'backend':'general';}
const comments=[],requests=[],votes=new Map();let current=null;
const visible=()=>posts.filter(p=>p.published||p.owner_id===current?.id);
const filter=(rows,params)=>rows.filter(row=>[...params].every(([key,value])=>['select','limit','offset','order'].includes(key)||value==='is.null'?value==='is.null'?row[key]==null:true:value.startsWith('eq.')?String(key==='metadata->>kind'?row.metadata?.kind:row[key])===value.slice(3):value.startsWith('in.(')?value.slice(4,-1).split(',').includes(row[key]):true));
const C={currentUser:()=>current,login:async(email)=>{current=users[email.split('@')[0]];return {...current,username:profiles.find(p=>p.user_id===current.id).username};},logout:async()=>{current=null;},claimUsername:async()=>profiles.find(p=>p.user_id===current.id).username,hydrateImages:async()=>{},
  request:async(path,options={})=>{requests.push({path,...options});const url=new URL(path,'https://test.example'),params=url.searchParams,body=options.body;
    if(path==='/auth/v1/user'){if(options.method==='PUT')Object.assign(current.user_metadata,body.data);return structuredClone(current);}
    if(path.includes('/rpc/')){const name=url.pathname.split('/').at(-1);
      if(name==='blog_feed'){let list=visible().filter(p=>(body.drafts?!p.published&&p.owner_id===current?.id:p.published)&&(!body.who||p.owner_id===body.who)&&(!body.board||p.collection===body.board)&&(!body.folder||p.folder_id===body.folder)&&(!body.search||(p.title+p.body).toLowerCase().includes(body.search.toLowerCase())));return {total:list.length,items:list.slice((body.page_number-1)*20,body.page_number*20).map(p=>{const {body:_,...summary}=p;const profile=profiles.find(x=>x.user_id===p.owner_id);return {...summary,username:profile.username,display_name:profile.display_name};})};}
      if(name==='blog_post_interactions')return posts.filter(p=>p.published&&body.post_ids.includes(p.id)).map(p=>({post_id:p.id,likes:[...votes].filter(([k,v])=>k.startsWith(p.id+':')&&v===1).length,dislikes:[...votes].filter(([k,v])=>k.startsWith(p.id+':')&&v===-1).length,mine:votes.get(p.id+':'+current?.id)||0,comments:comments.filter(c=>c.post_id===p.id&&!c.deleted).length}));
      if(name==='blog_react'){assert.ok(current);assert.ok(posts.some(p=>p.id===body.target&&p.published));const key=body.target+':'+current.id;if(body.reaction)votes.set(key,body.reaction);else votes.delete(key);return (await C.request('/rest/v1/rpc/blog_post_interactions',{body:{post_ids:[body.target]}}))[0];}
      if(name==='blog_usage')return {posts:2,textBytes:100,imageBytes:0,postLimit:100,textLimit:2097152,imageLimit:10485760};
      if(name==='blog_delete_comment'){const c=comments.find(c=>c.id===body.target);c.deleted=true;c.body='此评论已删除';return null;}
      if(name==='blog_file_operation'){const f=folders.find(f=>f.id===body.target_id);if(body.action==='delete_post'){const index=posts.findIndex(p=>p.id===body.target_id);assert.equal(posts[index].owner_id,current.id);assert.equal(posts[index].version,body.expected_version);posts.splice(index,1);}else if(body.action==='delete_folder'){assert.equal(f.owner_id,current.id);assert.equal(f.version,body.expected_version);assert.equal(folders.some(x=>x.parent_id===f.id),false);assert.equal(posts.some(x=>x.folder_id===f.id),false);folders.splice(folders.indexOf(f),1);}else if(body.action==='rename_folder'){f.name=body.new_name;f.version++;}else if(body.action==='move_folder'){f.parent_id=body.new_parent;f.version++;}return null;}
    }
    const table=url.pathname.split('/').at(-1);
    if(table==='blog_profiles'){const rows=filter(profiles,params);if(options.method==='PATCH'){Object.assign(rows[0],body);return rows;}return structuredClone(rows);}
    if(table==='blog_posts'){
      if(options.withCount){let rows=posts.filter(p=>p.published&&p.metadata.forum_sync===true&&['frontend','backend','ai','language','engineering','general'].includes(p.metadata.forum_section));const section=params.get('metadata->>forum_section');if(section.startsWith('eq.'))rows=rows.filter(p=>p.metadata.forum_section===section.slice(3));if(section.startsWith('in.'))rows=rows.filter(p=>section.slice(4,-1).split(',').includes(p.metadata.forum_section));const search=params.get('or')?.match(/title\.ilike\."\*(.*?)\*"/)?.[1];if(search)rows=rows.filter(p=>(p.title+p.summary+p.body).toLowerCase().includes(search.toLowerCase()));return {total:rows.length,data:structuredClone(rows.slice(Number(params.get('offset')),Number(params.get('offset'))+20))};}
      return structuredClone(filter(visible(),params));
    }
    if(table==='blog_folders')return structuredClone(filter(folders,params));
    if(table==='blog_comments'){if(options.method==='POST'){const c={...body,id:w.crypto.randomUUID(),author_id:current.id,deleted:false,created_at:'2026-10-02'};comments.unshift(c);return [c];}return structuredClone(filter(comments,params).slice(Number(params.get('offset')||0),Number(params.get('offset')||0)+21));}
    if(table==='blog_media')return [];
    throw Error('Unexpected request '+path);
  },
  save:async(payload,version)=>{let p=posts.find(p=>p.id===payload.id);if(p){assert.equal(p.owner_id,current.id);assert.equal(p.version,version);Object.assign(p,payload,{version:version+1});}else {p={...payload,version:1,created_at:'2026-10-02'};posts.push(p);}return structuredClone(p);},
  createFolder:async data=>{const folder={...data,version:1};folders.push(folder);return [folder];}
};
w.BlogCloud=C;
for(const file of ['vendor/marked.umd.js','vendor/purify.min.js','markdown.js','community-api.js','community-auth.js','community-app.js'])w.eval(await readFile(file,'utf8'));
const settle=async()=>{await new Promise(r=>setTimeout(r,30));const confirmation=d.querySelector('.delete-confirm[open]');if(confirmation){confirmation.querySelector('[data-confirm-delete]').click();await new Promise(r=>setTimeout(r,30));}};
async function go(hash){w.location.hash=hash;await settle();}
const submit=form=>form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
async function snapshot(name){if(!process.env.COMMUNITY_SNAPSHOT)return;const copy=d.documentElement.cloneNode(true);copy.querySelectorAll('script,.inline-message').forEach(el=>el.remove());await writeFile('.test-runtime/polish-'+name+'.html','<!doctype html>'+copy.outerHTML.replaceAll('href="./','href="../'));}
await settle();await snapshot('forum');assert.ok(d.querySelector('.forum-topic-table'));assert.equal(d.querySelector('#mega-panel'),null);assert.equal(d.querySelector('.site-switcher-menu'),null);d.querySelector('#account-button').click();assert.equal(d.querySelector('#account-popover').hidden,false);assert.match(d.querySelector('#account-popover').textContent,/个人资料我的空间登录/);d.querySelector('#account-button').click();assert.equal(d.querySelector('#account-popover').hidden,true);assert.equal(d.querySelectorAll('.community-post').length,20);assert.doesNotMatch(d.querySelector('main').textContent,/SECRET/);assert.ok(requests.some(r=>r.path.includes('forum_sync')));
await go('#/post/a-post');assert.ok(d.querySelector('.sidebar-content .document-tree'));assert.ok(d.querySelector('.file-pane .article-body'));
assert.ok(d.querySelector('[data-vote="1"]'));assert.equal(votes.size,0);assert.ok(d.querySelector('.space-tree details[open] a[aria-current="page"]'));assert.match(d.querySelector('.community-breadcrumb').textContent,/Alice folder/);await snapshot('reading');
await go('#/posts?section=language');assert.equal(d.querySelectorAll('.community-post').length,20);assert.match(d.querySelector('.forum-directory').textContent,/语言/);assert.doesNotMatch(d.querySelector('.forum-directory').textContent,/基础与工程|交流/);
profiles[1].featured_posts=['b-post','b-draft','a-post'];await go('#/u/bob?view=about');assert.equal(d.querySelectorAll('.about-post').length,1);assert.match(d.querySelector('.about-post').textContent,/Bob public/);assert.equal(d.querySelector('[data-about-edit]'),null);assert.doesNotMatch(d.querySelector('.about-page').textContent,/PRIVATE|Alice public/);
await go('#/posts?page=2');assert.equal(d.querySelectorAll('.community-post').length,4);
await go('#/u/bob');assert.match(d.querySelector('#nav .space-identity').textContent,/Bob/);assert.doesNotMatch(d.querySelector('.author-file-tree').textContent,/Alice public/);assert.equal(d.querySelector('[data-folder-create]'),null);assert.equal(d.querySelector('.community-feed'),null);
const navMutations=[];const observer=new w.MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1&&n.querySelector?.('a[href="#/posts"]'))navMutations.push(n.textContent);});observer.observe(d.querySelector('#nav'),{childList:true,subtree:true});await go('#/u/bob?view=moments');await go('#/u/bob?view=guestbook');await go('#/u/bob');observer.disconnect();assert.deepEqual(navMutations,[],'Author navigation must never rebuild global tabs during internal transitions');
await go('#/u/bob?board=knowledge');d.querySelector('.space-back').click();await settle();assert.equal(w.location.hash,'#/posts?page=2');await go('#/u/bob?board=knowledge');assert.match(d.querySelector('#nav .space-identity').textContent,/Bob的空间/);assert.equal(d.querySelector('#nav a[href="#/tools"]'),null);assert.ok(d.querySelector('.author-file-tree details details'));d.querySelector('[data-expand]').click();assert.equal(d.querySelectorAll('.author-file-tree details:not([open])').length,0);d.querySelector('[data-collapse]').click();assert.equal(d.querySelectorAll('.author-file-tree details[open]').length,0);
await go('#/post/b-post');assert.equal(d.querySelector('[data-edit]'),null);assert.ok(d.querySelector('[data-comment-login]'));assert.equal(d.querySelector('#comment-form'),null);
d.querySelector('[data-comment-login]').click();await snapshot('login');let form=d.querySelector('#inline-login');form.elements.email.value='alice@example.test';form.elements.password.value='test-only';submit(form);await settle();
assert.equal(current.id,aid);await go('#/space');await settle();assert.match(w.location.hash,/#\/u\/alice/);await go('#/u/bob?view=guestbook');d.querySelector('.space-back').click();await settle();assert.equal(w.location.hash,'#/posts?page=2');assert.equal(d.querySelector('#nav.author-nav'),null);assert.ok(d.querySelector('#nav a[href="#/posts"][aria-current=page]'));await go('#/');await go('#/space');await settle();await go('#/u/alice?view=moments');d.querySelector('.space-back').click();await settle();assert.equal(w.location.hash,'#/');assert.ok(d.querySelector('.home-art'));await go('#/tools');await go('#/space');await settle();d.querySelector('.space-back').click();await settle();assert.equal(w.location.hash,'#/tools');await go('#/post/b-post');assert.ok(d.querySelector('#comment-form'));assert.equal(d.querySelector('[data-edit]'),null);
d.querySelector('[data-vote="1"]').click();await settle();assert.equal(d.querySelector('[data-vote="1"]').getAttribute('aria-pressed'),'true');assert.match(d.querySelector('[data-vote="1"]').textContent,/1/);d.querySelector('[data-vote="-1"]').click();await settle();assert.equal(d.querySelector('[data-vote="1"]').getAttribute('aria-pressed'),'false');assert.equal(d.querySelector('[data-vote="-1"]').getAttribute('aria-pressed'),'true');d.querySelector('[data-vote="-1"]').click();await settle();assert.equal(votes.size,0);
form=d.querySelector('#comment-form');form.elements.body.value='Hello Bob';submit(form);await settle();assert.match(d.querySelector('.comment-list').textContent,/Hello Bob/);assert.equal(comments[0].author_id,aid);assert.equal(comments[0].post_id,'b-post');assert.match(d.querySelector('[data-comment-jump]').textContent,/1/);
d.querySelector('[data-reply]').click();form=d.querySelector('#comment-form');assert.equal(form.querySelector('#reply-to').hidden,false);form.elements.body.value='Reply';submit(form);await settle();assert.ok(comments[0].parent_id);
d.querySelector('[data-delete-comment]').click();await settle();assert.equal(comments[0].deleted,true);assert.equal(d.querySelector('[data-comment="'+comments[0].id+'"]'),null);assert.doesNotMatch(d.querySelector('.comment-list').textContent,/此评论已删除/);
await go('#/u/bob?board=knowledge');assert.equal(d.querySelector('[data-write]'),null);await go('#/u/alice?board=knowledge');d.querySelector('[data-tree-new-post]').click();await settle();form=d.querySelector('#community-editor');assert.ok(form);assert.doesNotMatch(form.elements.folder.innerHTML,/Bob folder/);
assert.equal(form.elements.visibility.value,'private');assert.equal(form.querySelector('.editor-top'),null);assert.equal(form.querySelector('.editor-path'),null);form.elements.visibility.value='public';form.elements.title.value='Own new post';form.elements.body.value='Own new body';form.elements.body.dispatchEvent(new w.Event('input',{bubbles:true}));form.querySelector('[data-mode=split]').click();assert.match(d.querySelector('#editor-preview').textContent,/Own new body/);submit(form);await settle();assert.equal(posts.at(-1).owner_id,aid);assert.match(w.location.hash,/#\/post\//);assert.ok(d.querySelector('.article-body'));
const newlySaved=posts.at(-1);assert.equal(newlySaved.published,true);assert.equal(newlySaved.metadata.forum_sync,false);
await go('#/posts');assert.doesNotMatch(d.querySelector('.community-feed').textContent,/Own new post/);
await go('#/edit/'+newlySaved.id);form=d.querySelector('#community-editor');form.elements.forumSync.checked=true;form.elements.forumSync.dispatchEvent(new w.Event('change'));assert.equal(form.elements.forumSection.required,true);assert.equal(form.reportValidity(),false);form.elements.forumSection.value='ai';submit(form);await settle();
await go('#/posts?section=ai');assert.match(d.querySelector('.community-feed').textContent,/Own new post/);assert.equal(d.querySelectorAll('.community-post').length,1);
await go('#/edit/'+newlySaved.id);form=d.querySelector('#community-editor');form.elements.forumSync.checked=false;form.elements.forumSync.dispatchEvent(new w.Event('change'));submit(form);await settle();assert.equal(posts.find(p=>p.id===newlySaved.id).published,true);await go('#/posts?section=ai');assert.equal(d.querySelectorAll('.community-post').length,0);
await go('#/u/alice');
await go('#/u/alice?view=about');d.querySelector('[data-about-edit]').click();let aboutForm=d.querySelector('#about-form');assert.doesNotMatch(aboutForm.elements.post.textContent,/SECRET draft|Bob public/);aboutForm.elements.bio.value='Backend engineer';aboutForm.elements.post.value='a-post';aboutForm.querySelector('[data-about-add]').click();aboutForm.elements.post.value=newlySaved.id;aboutForm.querySelector('[data-about-add]').click();aboutForm.querySelector('[data-up="1"]').click();submit(aboutForm);await settle();assert.deepEqual(Array.from(profiles[0].featured_posts),[newlySaved.id,'a-post']);assert.equal(d.querySelectorAll('.about-post').length,2);assert.match(d.querySelector('.about-post').textContent,/Own new post/);await snapshot('about');await go('#/u/alice');
const context=el=>el.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:100,clientY:180}));
const choose=text=>[...d.querySelectorAll('.tree-context-menu button')].find(b=>b.textContent===text).click();
context(d.querySelector('[data-post-menu="a-post"]'));choose('删除');assert.ok(d.querySelector('.delete-confirm[open]'));assert.equal(d.activeElement,d.querySelector('.delete-confirm [data-cancel]'));d.querySelector('.delete-confirm [data-cancel]').click();await settle();assert.ok(posts.find(p=>p.id==='a-post'));assert.equal(d.querySelector('.delete-confirm'),null);
context(d.querySelector('[data-post-menu="a-post"]'));choose('重命名');
let rename=d.querySelector('.tree-rename');rename.value='Renamed file';rename.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await settle();assert.equal(posts.find(p=>p.id==='a-post').title,'Renamed file');assert.match(posts.find(p=>p.id==='a-post').body,/Alice body/);
context(d.querySelector('[data-folder-menu="a-folder"]'));choose('重命名');rename=d.querySelector('.tree-rename');rename.value='Renamed folder';rename.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await settle();assert.equal(folders.find(f=>f.id==='a-folder').name,'Renamed folder');
context(d.querySelector('.document-tree'));assert.deepEqual([...d.querySelectorAll('.tree-context-menu button')].map(b=>b.textContent),['新建文件','新建文件夹']);d.querySelector('.tree-context-menu button').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('.tree-context-menu'),null);
context(d.querySelector('[data-folder-menu="a-folder"]'));choose('新建文件');await settle();assert.equal(d.querySelector('#community-editor').elements.folder.value,'a-folder');
await go('#/u/bob');context(d.querySelector('.document-tree'));assert.equal(d.querySelector('.tree-context-menu'),null);
await go('#/edit/a-post');form=d.querySelector('#community-editor');assert.equal(form.querySelector('.editor-metadata').open,false);await snapshot('editor');const filePane=d.querySelector('.file-pane'),hashBefore=w.location.hash;d.querySelector('details[data-tree-folder] summary>a').click();assert.equal(w.location.hash,hashBefore);assert.equal(d.querySelector('.file-pane'),filePane);form.elements.body.value='Recover this';form.elements.body.dispatchEvent(new w.Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,650));assert.match(d.querySelector('#save-state').textContent,/备份/);await go('#/post/a-post');assert.match(d.querySelector('.article-body').textContent,/Alice body/);
await go('#/settings');await snapshot('settings');assert.ok(d.querySelector('[data-restore="a-post"]'));form=d.querySelector('#profile-form');form.elements.display_name.value='Alice changed';submit(form);await settle();assert.equal(profiles[0].display_name,'Alice changed');assert.equal(d.querySelector('#profile-form').elements.display_name.value,'Alice changed');assert.match(d.querySelector('.profile-identity').textContent,/Alice changed/);assert.match(d.querySelector('#account-button').getAttribute('aria-label'),/Alice changed/);assert.equal(d.querySelector('.profile-management').open,false);
d.querySelector('[data-restore="a-post"]').click();await settle();form=d.querySelector('#community-editor');assert.equal(form.elements.body.value,'Recover this');form.elements.visibility.value='private';submit(form);await settle();assert.equal(posts[0].published,false);assert.equal(d.querySelector('[data-post-interactions]'),null);assert.equal(d.querySelector('#comment-form'),null);await go('#/posts');assert.doesNotMatch(d.querySelector('.community-feed').textContent,/Renamed file/);
await go('#/u/alice?board=knowledge');d.querySelector('[data-tree-new-folder]').click();form=d.querySelector('dialog[open] form');form.elements.name.value='New collection';submit(form);await settle();assert.equal(folders.at(-1).owner_id,aid);assert.match(d.querySelector('.document-tree').textContent,/New collection/);assert.equal(d.querySelector('.document-directory'),null);
context(d.querySelector('[data-folder-menu="'+folders.at(-1).id+'"]'));choose('移动');form=d.querySelector('dialog[open] form');form.elements.name.value='Renamed collection';submit(form);await settle();assert.equal(folders.at(-1).name,'Renamed collection');
const rootFolder=folders.at(-1).id;d.querySelector('[data-tree-new-folder]').click();form=d.querySelector('dialog[open] form');form.elements.name.value='Child folder';submit(form);await settle();assert.equal(folders.at(-1).parent_id,rootFolder);const childFolder=folders.at(-1).id;d.querySelector('[data-tree-new-folder]').click();form=d.querySelector('dialog[open] form');form.elements.name.value='Grandchild folder';submit(form);await settle();assert.equal(folders.at(-1).parent_id,childFolder);const grandchildFolder=folders.at(-1).id;d.querySelector('[data-tree-new-post]').click();await settle();form=d.querySelector('#community-editor');assert.equal(form.elements.folder.value,grandchildFolder);form.elements.title.value='Nested private post';form.elements.body.value='Draft';form.elements.visibility.value='private';submit(form);await settle();await go('#/u/alice');assert.match(d.querySelector('.author-file-tree').textContent,/Nested private post/);assert.ok(d.querySelector('.author-file-tree details details details'));await snapshot('nested-files');
form=d.querySelector('#scoped-search');form.elements.q.value='Nested private';submit(form);await settle();assert.match(d.querySelector('.author-file-tree').textContent,/Grandchild folder/);assert.equal(d.querySelectorAll('.author-file-tree .post-node').length,1);
await go('#/u/alice?folder='+rootFolder);context(d.querySelector('[data-folder-menu="'+rootFolder+'"]'));choose('移动');d.querySelector('[data-delete-folder]').click();await settle();assert.equal(folders.some(f=>[rootFolder,childFolder,grandchildFolder].includes(f.id)),false);assert.equal(posts.some(p=>p.title==='Nested private post'),false);assert.ok(folders.some(f=>f.owner_id===bid));
await go('#/moments');form=d.querySelector('#moment-form');assert.ok(form);form.elements.body.value='A short thought';submit(form);await settle();assert.equal(posts.at(-1).metadata.kind,'moment');assert.match(d.querySelector('.moments-feed').textContent,/A short thought/);assert.doesNotMatch(d.querySelector('.moments-feed').textContent,/Essay 1/);await snapshot('moments');await go('#/u/bob?view=moments');assert.equal(d.querySelector('#moment-form'),null);assert.doesNotMatch(d.querySelector('.moments-feed').textContent,/A short thought/);assert.match(d.querySelector('#nav').textContent,/Bob的空间/);await go('#/u/alice?view=moments');assert.match(d.querySelector('.moments-feed').textContent,/A short thought/);
await go('#/write?board=tools');form=d.querySelector('#community-editor');form.elements.title.value='Useful tool';form.elements.toolURL.value='https://example.com/tool';form.elements.body.value='Tool review';form.elements.body.dispatchEvent(new w.Event('input',{bubbles:true}));submit(form);await settle();assert.ok(d.querySelector('.hero-actions a[href="https://example.com/tool"]'));
await go('#/write?board=photos');form=d.querySelector('#community-editor');form.elements.visibility.value='public';form.elements.title.value='Photo';form.elements.body.value='![image](media:owner/image.webp)';form.elements.body.dispatchEvent(new w.Event('input',{bubbles:true}));submit(form);await settle();assert.equal(posts.at(-1).metadata.cover,'owner/image.webp');await go('#/photos');assert.ok(d.querySelector('.gallery-cover'));
await go('#/u/bob?view=guestbook');form=d.querySelector('#comment-form');form.elements.body.value='Space message';submit(form);await settle();assert.equal(comments[0].space_id,bid);assert.equal(comments[0].post_id,null);
await go('#/guestbook');form=d.querySelector('#comment-form');form.elements.body.value='Site message';submit(form);await settle();assert.equal(comments[0].space_id,null);
await go('#/edit/b-post');assert.match(d.querySelector('main').textContent,/只能编辑自己的帖子/);
const publishedOwn=posts.find(p=>p.owner_id===aid&&p.published);await go('#/edit/'+publishedOwn.id);form=d.querySelector('#community-editor');form.elements.body.value='Keyboard updated published post';form.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true,cancelable:true}));await settle();assert.equal(publishedOwn.published,true);assert.equal(publishedOwn.body,'Keyboard updated published post');
await go('#/edit/a-post');form=d.querySelector('#community-editor');form.elements.body.value='Keyboard saved draft';form.elements.body.dispatchEvent(new w.Event('input',{bubbles:true}));form.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true,cancelable:true}));await settle();assert.equal(posts[0].body,'Keyboard saved draft');assert.equal(posts[0].published,false);assert.equal(d.querySelector('[data-post-interactions]'),null);assert.ok(d.querySelector('.article-body'));
d.querySelector('#account-button').click();assert.match(d.querySelector('#account-popover').textContent,/登出/);d.querySelector('[data-account-auth]').click();await settle();assert.equal(d.querySelector('#comment-form'),null);await go('#/post/a-draft');assert.match(d.querySelector('main').textContent,/不存在|公开/);
await go('#/knowledge');form=d.querySelector('#scoped-search');form.elements.q.value='Bob';submit(form);await settle();assert.equal(d.querySelectorAll('.community-post').length,1);assert.ok(requests.some(r=>r.path.includes('or=')));
await go('#/knowledge?q=not-a-real-match');assert.ok(d.querySelector('.forum-empty a'));assert.match(d.querySelector('.forum-empty').textContent,/没有找到/);
await go('#/');assert.ok(d.querySelector('.home-art'));assert.equal(d.querySelector('main').textContent,'');await go('#/posts');assert.ok(d.querySelector('.community-feed'));assert.equal(d.body.classList.contains('is-home'),false);
if(process.env.COMMUNITY_SNAPSHOT){await go('#/u/bob?board=knowledge');await snapshot('listing');d.documentElement.dataset.theme='dark';await snapshot('dark');delete d.documentElement.dataset.theme;await go('#/');await snapshot('home');}
dom.window.close();console.log('PASS: real community UI routes, paged feeds, author spaces, login-gated comments/replies, owner-only edit, publish-to-read, restore, folders, tools, photo covers, guestbooks, logout and scoped search.');
