import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PGlite} from './.test-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
alter table storage.objects enable row level security;grant usage on schema storage to anon,authenticated;grant select,insert,delete on storage.objects to anon,authenticated;`);
for(const file of ['schema','file-operations','registration','images'])await db.exec(await readFile('supabase/'+file+'.sql','utf8'));
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002',U='00000000-0000-0000-0000-000000000003',N='00000000-0000-0000-0000-000000000004';
await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${A}','a@test.example',now()),('${B}','b@test.example',now()),('${U}','u@test.example',null),('${N}','n@test.example',now());update auth.users set is_anonymous=true where id='${N}';insert into blog_authors values('${A}');insert into blog_folders(id,collection,name) values('legacy','knowledge','Legacy');insert into blog_posts(id,collection,folder_id,title,published) values('legacy-post','knowledge','legacy','Preserved',true);`);
const migration=await readFile('supabase/community.sql','utf8');await db.exec(migration);await db.exec(migration);
const storageFix=await readFile('supabase/community-storage-fix.sql','utf8');await db.exec(storageFix);await db.exec(storageFix);
assert.equal((await db.query("select file_size_limit from storage.buckets where id='blog-images'")).rows[0].file_size_limit,1048576);
assert.equal((await db.query("select owner_id from blog_posts where id='legacy-post'")).rows[0].owner_id,A);
async function role(name,id=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+name);}
async function fail(sql,values=[]){await assert.rejects(db.query(sql,values));}
await role('authenticated',A);
// PostgREST return=representation applies SELECT RLS during INSERT. The
// recursive stable visibility helper cannot see that statement's new row.
await fail("insert into blog_folders(id,collection,name) values('returning-folder','knowledge','Returning') returning *");
await db.query("insert into blog_folders(id,collection,name) values('returning-folder','knowledge','Returning')");
assert.equal((await db.query("select * from blog_folders where id='returning-folder'")).rows.length,1);
await db.query("select blog_file_operation('delete_folder','returning-folder',1)");
await db.exec("insert into blog_folders(id,collection,name) values('a-root','knowledge','Same'),('a-private','knowledge','Private');insert into blog_folders(id,collection,name,parent_id) values('a-child','knowledge','Child','a-root');insert into blog_posts(id,collection,folder_id,title,body,published) values('a-public','knowledge','a-child','Public','Search secrettext',true),('a-draft','knowledge','a-private','Private title','DRAFT BODY',false);");
await role('authenticated',B);
await db.exec("insert into blog_folders(id,collection,name) values('b-root','knowledge','Same');insert into blog_posts(id,collection,folder_id,title,body,published) values('b-public','knowledge','b-root','B public','B body',true),('b-draft','knowledge','b-root','B draft','B SECRET',false);");
assert.equal((await db.query("select * from blog_posts where id='a-draft'")).rows.length,0);
assert.equal((await db.query("update blog_posts set title='attack' where id='a-public' returning id")).rows.length,0);
await fail("insert into blog_posts(id,owner_id,collection,title) values('spoof',$1,'knowledge','Spoof')",[A]);
await fail("insert into blog_posts(id,collection,folder_id,title) values('cross','knowledge','a-child','Cross')");
await fail("insert into blog_folders(id,collection,parent_id,name) values('cross','knowledge','a-root','Cross')");
await fail("select blog_file_operation('rename_folder','a-root',1,'Attack')");
await fail("select blog_file_operation('delete_post','a-public',1)");
await role('authenticated',A);
await fail("update blog_posts set owner_id=$1 where id='a-public'",[B]);
await fail("select blog_file_operation('move_folder','a-root',1,null,'a-child')");
await fail("select blog_file_operation('move_folder','a-root',1,null,'b-root')");
await db.query("select blog_file_operation('rename_folder','a-root',1,'Renamed')");
await fail("select blog_file_operation('rename_folder','a-root',1,'Stale')");
await fail("select blog_file_operation('delete_folder','a-root',2)");
await role('anon');
assert.equal((await db.query("select * from blog_folders where id='a-root'")).rows.length,1);
assert.equal((await db.query("select * from blog_folders where id='a-private'")).rows.length,0);
const feed=(await db.query("select blog_feed(null,null,null,'secrettext',false,1) as data")).rows[0].data;
assert.equal(feed.items.length,1);assert.equal(feed.items[0].id,'a-public');assert.equal('body' in feed.items[0],false);
assert.equal((await db.query("select blog_feed(null,null,null,'',true,1) as data")).rows[0].data.total,0);
await fail("insert into blog_comments(body) values('anonymous')");
for(const who of [U,N]){await role('authenticated',who);await fail("insert into blog_posts(id,collection,title) values('unverified','essays','No')");await fail("insert into blog_comments(body) values('No')");await fail("select blog_reserve_image(100)");}
await role('authenticated',B);
await fail("insert into blog_comments(post_id,body) values('a-draft','No')");
const comment=(await db.query("insert into blog_comments(post_id,body) values('a-public','Comment from B') returning id")).rows[0].id;
await fail("insert into blog_comments(body) values('too fast')");
await role('authenticated',A);
const reply=(await db.query("insert into blog_comments(post_id,parent_id,body) values('a-public',$1,'Reply from A') returning id",[comment])).rows[0].id;
await db.query('select blog_delete_comment($1)',[comment]);
assert.equal((await db.query('select body,deleted from blog_comments where id=$1',[comment])).rows[0].deleted,true);
await role('authenticated',B);await fail('select blog_delete_comment($1)',[reply]);
await db.query("select blog_delete_comment($1)",[comment]);
await role('anon');await fail('select blog_delete_comment($1)',[reply]);
await role('authenticated',A);
await db.query("update blog_profiles set display_name='作者 A',bio='Bio' where user_id=$1",[A]);
assert.equal((await db.query("update blog_profiles set display_name='Hacked' where user_id=$1 returning user_id",[B])).rows.length,0);
await fail("update blog_profiles set username='stolen'");
const image=(await db.query('select blog_reserve_image(1000) as path')).rows[0].path;
assert.equal((await db.query('select blog_usage() as data')).rows[0].data.imageBytes,1048576);
// Storage preflight tests RLS before server-generated size exists, then rolls back.
await db.exec('begin');await db.query("insert into storage.objects(bucket_id,name) values('blog-images',$1)",[image]);await db.exec('rollback');
await db.query("insert into storage.objects(bucket_id,name,metadata) values('blog-images',$1,'{\"size\":1000}')",[image]);
await db.query('select blog_settle_images()');assert.equal((await db.query('select blog_usage() as data')).rows[0].data.imageBytes,1000);
await role('authenticated',B);
assert.equal((await db.query('select * from blog_media')).rows.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await fail("insert into storage.objects(bucket_id,name,metadata) values('blog-images',$1,'{\"size\":500}')",[image]);
await role('authenticated',A);await db.query("update blog_posts set body=$1 where id='a-public'",['![image](media:'+image+')']);
await role('anon');assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await role('authenticated',A);assert.equal((await db.query("delete from storage.objects where name=$1 returning id",[image])).rows.length,0);
await db.query("update blog_posts set published=false where id='a-public'");await role('anon');assert.equal((await db.query('select * from storage.objects')).rows.length,0);
assert.equal((await db.query('select * from blog_comments')).rows.length,0);
await role('authenticated',A);await db.query("update blog_posts set body='' where id='a-public'");await db.query('delete from storage.objects where name=$1',[image]);await db.query('select blog_release_image($1)',[image]);
assert.equal((await db.query('select blog_usage() as data')).rows[0].data.imageBytes,0);
for(let i=0;i<10;i++)await db.query('select blog_reserve_image(1048576)');await fail('select blog_reserve_image(1)');
await fail('select blog_reserve_image(1048577)');
await role('authenticated',B);
for(let i=0;i<25;i++)await db.query("insert into blog_posts(id,collection,title,published) values($1,'essays',$1,true)",['page-'+String(i).padStart(2,'0')]);
const page1=(await db.query("select blog_feed($1,'essays',null,'',false,1) as data",[B])).rows[0].data;
const page2=(await db.query("select blog_feed($1,'essays',null,'',false,2) as data",[B])).rows[0].data;
assert.equal(page1.total,25);assert.equal(page1.items.length,20);assert.equal(page2.items.length,5);assert.equal(new Set([...page1.items,...page2.items].map(p=>p.id)).size,25);
// Quota includes metadata; cannot evade by placing text in metadata.
for(let i=0;i<10;i++)await db.query("insert into blog_posts(id,collection,title,body) values($1,'essays','Large',$2)",['large-'+i,'x'.repeat(190000)]);
await fail("insert into blog_posts(id,collection,title,body) values('over','essays','Large',$1)",['x'.repeat(200000)]);
await db.close();console.log('PASS: repeatable legacy migration, two-user isolation, anonymous/unverified denial, ownership FKs, comments/replies/moderation, drafts, private images, byte quotas, server search and disjoint pagination.');
